# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  generate-library:
    parameters:
      library:
        type: string
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Generate << parameters.library >> API Client 
          command: |
            docker run --rm -v "$CIRCLE_WORKING_DIRECTORY:/local" openapitools/openapi-generator-cli batch --clean /local/<< parameters.library >>.yaml
      - persist_to_workspace:
          root: out
          paths:
            - "<< parameters.library >>"

  validate-typescript:
    docker: 
      - image: cimg/node:18.14
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -al /tmp/workspace
      - run:
          name: Build the Generated API Client
          working_directory: /tmp/workspace/typescript
          command: npm i && npm run build  

  determine-release-version:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Derive next version from Tag
          command: echo -n "<< pipeline.git.tag >>" | cut -d 'v' -f2 > /tmp/workspace/DERIVED_NEXT_VERSION
          working_directory: /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - DERIVED_NEXT_VERSION

  release-typescript:
    docker: 
      - image: cimg/node:18.14
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Version Check
          command: |
            CURRENT_VERSION=$(npm pkg get version | tr -d '"')
            if [[ "$CURRENT_VERSION" == "$(cat /tmp/workspace/DERIVED_NEXT_VERSION)" ]] ; then echo "Already at Version $(cat /tmp/workspace/DERIVED_NEXT_VERSION)." && exit 1; fi
          working_directory: /tmp/workspace/typescript
      - run:
          name: Set Release Version
          command: npm version $(cat /tmp/workspace/DERIVED_NEXT_VERSION)
          working_directory: /tmp/workspace/typescript
      - run:
          name: Build & Publish the API Client to NPM
          working_directory: /tmp/workspace/typescript
          command: |
            npm i 
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish --access public
            

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-all:
    jobs:
      - generate-library:
          matrix:
            parameters:
              library: [typescript]
      - validate-typescript:
          requires:
            - generate-library
  release-all:
    jobs:
      - generate-library:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          matrix:
            parameters:
              library: [typescript]
      - validate-typescript:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - generate-library
      - determine-release-version:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - validate-typescript
      - release-typescript:
          context:
            - auditjs
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - determine-release-version